application: polymer-project
version: ajaxify
runtime: python27
api_version: 1
threadsafe: yes

#default_expiration: "0s"

libraries:
- name: PIL
  version: latest

#inbound_services:
#- warmup

handlers:

# Top-level URLs ---------------------------------------------------------------
- url: /$
  static_files: _site/index.html
  upload: _site/index\.html

- url: /build/$
  static_files: _site/build/index.html
  upload: _site/build/index\.html

- url: /build/(.*)
  script: build.application

# Short URLs -------------------------------------------------------------------
- url: /platform(.min)?.js
  static_files: components/platform/platform.js
  upload: components/platform/platform\.js
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /platform(.min)?.js.map
  static_files: components/platform/platform.js.map
  upload: components/platform/platform\.js.\map
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /polymer(.min)?.(js|html)
  static_files: components/polymer/polymer.\2
  upload: components/polymer/polymer\.(js|html)
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /polymer(.min)?.js.map
  static_files: components/polymer/polymer.js.map
  upload: components/polymer/polymer\.js\.map
  http_headers:
    Access-Control-Allow-Origin: "*"

# ------------------------------------------------------------------------------

# # Map minified polymer to minified version.
# # This also preservers old URL (/polymer/polymer.min.js)
# # COMMENT OUT TO TEST UNIMINIFIED Polymer
# - url: /(polymer-all\/)?polymer/polymer(.min)?.js
#   static_files: components/polymer/polymer.js
#   upload: components/polymer/polymer\.js

# / Elements -------------------------------------------------------------------
# - url: /(polymer-all\/)?(polymer|polymer-ui|more)-elements/(.*)
#   static_files: polymer-all/\1-elements/\2
#   upload: polymer-all/(polymer|polymer-ui|more)-elements/(.*)
#   http_headers:
#     Access-Control-Allow-Origin: "*"

# - url: /(toolkit-ui|web-animations-js)/(.*)
#   static_files: polymer-all/\1/\2
#   upload: polymer-all/(toolkit-ui|web-animations-js)/(.*)
#   http_headers:
#     Access-Control-Allow-Origin: "*"

# /tools -----------------------------------------------------------------------
  #curl https://polymer-project.org/tools/pull-all.sh | bash
#- url: /tools/pull-all\.sh$
#  static_files: polymer-all/tools/bin/pull-all.sh
#  upload: polymer-all/tools/bin/pull-all\.sh

- url: /tools/sandbox/$
  static_files: polymer-all/projects/sandbox/index.html
  upload: index\.html

- url: /tools/sandbox/(.*)
  static_files: polymer-all/projects/sandbox/\1
  upload: (.*)/index.html

# Map raw paths with trailing "/" to an index.html file.
- url: /(.*)/$
  static_files: _site/\1/index.html
  upload: _site/(.*)/index.html

- url: /polymer-all
  static_dir: polymer-all
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /samples
  static_dir: samples
  http_headers:
    Access-Control-Allow-Origin: "*"

# New mappings for Bower
- url: /components
  static_dir: components
  http_headers:
    Access-Control-Allow-Origin: "*"

# All other URLs map directly to their path in _site/.
- url: /
  static_dir: _site
  http_headers:
    Access-Control-Allow-Origin: "*"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?node_modules/.*
- ^(.*/)?third_party/closure/.*
- ^scripts/.*
- ^(.*/)?\.md

# few extras to reduce number of files uploaded.
- ^(.*/)?.*\.sublime-project
- ^(.*/)?.*\.sublime-workspace
- ^(.*/)?platform-dev/workbench/.*
- ^(.*/)?(AUTHORS|LICENSE|PATENTS|COPYING)$
